name: ci

on:
  # Triggers the workflow every Sunday at 23:42
  schedule:
    - cron: "42 23 * * 0"

jobs:
  build-tags:
    strategy:
      matrix:
        refs:
          - refs/tags/v1.7.1

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.refs }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date --rfc-3339=seconds | sed 's/ /T/')" >> $GITHUB_ENV

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/docker/frontend.Dockerfile
          build-args: |
            APP_VERSION=${{ env.VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REV=${{ github.sha }}
            GIT_REF_NAME=${{ github.ref }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/strichliste-frontend:${{ env.VERSION }}
      
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/docker/backend.Dockerfile
          build-args: |
            APP_VERSION=${{ env.VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REV=${{ github.sha }}
            GIT_REF_NAME=${{ github.ref }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/strichliste-backend:${{ env.VERSION }}
  
  build-latest:
    strategy:
      matrix:
        refs:
          - refs/heads/main

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.refs }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date --rfc-3339=seconds | sed 's/ /T/')" >> $GITHUB_ENV

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/docker/frontend.Dockerfile
          build-args: |
            APP_VERSION=${{ env.VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REV=${{ github.sha }}
            GIT_REF_NAME=${{ github.ref }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/strichliste-frontend:latest
      
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/docker/backend.Dockerfile
          build-args: |
            APP_VERSION=${{ env.VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REV=${{ github.sha }}
            GIT_REF_NAME=${{ github.ref }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/strichliste-backend:latest
