name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.BASE_DIR }}
          file: ${{ env.BASE_DIR }}/docker/frontend.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.USER }}/${{ env.REPO }}/frontend:latest
            ghcr.io/${{ env.USER }}/${{ env.REPO }}/frontend:${{ env.VERSION }}
      
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.BASE_DIR }}
          file: ${{ env.BASE_DIR }}/docker/backend.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.USER }}/${{ env.REPO }}/backend:latest
            ghcr.io/${{ env.USER }}/${{ env.REPO }}/backend:${{ env.VERSION }}